#before running the docker-compose up use docker-compose rm -svf
version: '3'
services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  # data-ingestion:
  #   deploy:
  #     replicas: 1    
  #   build: DataIngestionandLoading
  #   container_name: data-ingestion_container
    
  # model-geneator:
  #   image: model-generator
  #   restart: always

  model-predictor:
    deploy:
      replicas: 1
    build: predictor
    container_name: model-predictor_container
    ports:
      - "9999:9999"
    networks:
      net_pet:
        ipv4_address: 172.27.1.19

networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16